version: "3"
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${DB_WIKI_PASSWORD}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2.5
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_WIKI_PASSWORD}
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8081:3000"


